### ISSUE TITLE
Why Storeon

### ISSUE THREAD

**Issue by mrjjwright** [johannschopplich/plain-spa#1]
Hi this is really cool.  Curious why you use storeon, is it just for the routing?  Didn’t notice you storing anything in it, not even todos.  In general, how could this lib pair with sinuous in an app?

**Comment by johannschopplich** [comment]
Hey there!

Thanks for asking. Currently, Storeon is singly used for the router, yes. It came into play for the todo list at some point, but I scrapped this draft: The toto app should display Sinuous' reactive capabilities, not Storeon's.

Since Storeon Router is based on Storeon, I will most likely keep this library for the router alone (since it's also that small). Besides, I'm sure setting up a global or local store is highly probable when creating a project on top of this template. For that another Storeon instance can simply initiated: https://github.com/storeon/storeon#readme

Hope that helps. If you prefer a different approach, feel free to share it!

**Comment by mrjjwright** [comment]
Thanks for the response!  I was curious as to ways to combine redux like stores with Sinuous was the only reason I was asking.  Your reasoning makes great sense.

**Comment by mindplay-dk** [comment]
Correct me if I'm wrong, but...

Using a `pushState`-based router seems to imply you're using SSR? It changes the browser URL, which means the server has to respond for those URLs, in case the user bookmarks one of them.

You probably got around this by setting up the server side to respond with the same static HTML for every URL? That addresses the problem, but you're now serving many different URLs for no practical reason - for example, this has no value in terms of SEO, as every URL served is a blank shell.

Serving actual content would require a build-step, and then we're sort of back to square one, I think?

Personally, if I'm building an SPA that's just an app, where SEO is not a concern, but I want to enable users to bookmark their location in the app, I still prefer hash-based routing. (Which can be done [very simply](https://codesandbox.io/s/sinuous-router-g2eud) using Sinuous state.)

This may be more a matter of opinion, but I also personally find it confusing when more state is hidden in the navigation history than is apparent from looking at the URL - and I also don't believe you should pack more data into the URL than necessary, perhaps at the most a search term and page number, which I would never want to hide in history state, since that defies bookmarking.

Overall, I think I'm somewhat unconvinced of the value of history state, although I realize maybe that's very opinionated. 😉

But in the context of trying to build an SPA with no build-step. Does it make sense? Might it make more sense to use an old-fashioned, bookmark-friendly URL hash pointing to a single server-side resource? 🤔

**Comment by johannschopplich** [comment]
First and foremost: thanks for your detailed comment. Let me share my view.

Well, using SSR would imply generating HTML on the server, which this project doesn't do. Utilizing the push state alone does not conclude to SSR usage. In fact, for SSR to work (precompiled HTML out of hyperscript), a build process would be necessary.

Many SPA's on the interweb do use the push state. I see hash-based routing rarely.

Indeed, a web server is required to make bookmarking work. But that's the beauty: Apache or Nginx is used by many users and probably installed by default on any shared environment. Even the official Vue documentation lists [example server](https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations) configurations. You're right, all routes will respond the same `index.html` and the frontend will evaluate the route again. I understand if that puts you off.

SPA's are often not optimized for SEO, but that's an issue regarding the architecture of an SPA, not this project in specific. A standard Vue or React (or sinuous) SPA is not optimized for search engines. This project doesn't differ. Sure, if SEO is an concern, I'd use a completely different setup. *Then* SSR or an SSG would be preferable. Like, for example an [Kirby Vue integration](https://github.com/johannschopplich/aria-kirby-vue-starterkit). Shameless plug. 😏

Which history mode to use is prererence, I agree. I like the look of native routes, but I get your point. I want to show, that a SPA *with* push-state routing is possible, without a build step. I'm aware of that sinuous example. 🙂  If I can get away with just some lines of [Apache configuration](https://github.com/johannschopplich/plain-spa/blob/master/.htaccess), I'm definitely in!

> But in the context of trying to build an SPA with no build-step. Does it make sense? Might it make more sense to use an old-fashioned, bookmark-friendly URL hash pointing to a single server-side resource? 🤔

In my opinion it does makes sense if one wants to use the HTML5 history mode but still doesn't want to generate anything on the server-side. Just plug'n'play. This project is a proof of concept to skip the build step while getting (almost) everything in return what e.g. React SPA's offer.

I think we both want to achieve the same — a minimal modern setup. 🙂 I hope I replied to all of your comments.

Edit: Revisiting the sinuous hash routing example I realized that you've created it. Wow!

P. S.: A better approach than my current setup would probably be importing the latest sinuous modules via Pikapkg or Snowpack and track them in the repository. But I don't want that dependency right now for the current concept.

**Comment by mrjjwright** [comment]
I love the lack of dependencies and think in general having such a lack is way underrated.

**Comment by mrjjwright** [comment]
I love the lack of dependencies and think in general that concept that is way underrated.   But

**Comment by mindplay-dk** [comment]
Thanks for the detailed reply! I appreciate you taking the time to discuss this. 🙂

Your points are well taken. I think the only point where I'd have to firmly disagree, is with the idea of serving the same document from many URLs - this is bad for caching, and can be harmful to SEO.

It seems fundamentally at odds with the idea of URLs being *unique* resource locators. By design, you're sending the wrong information to the server - since there's really only one server resource, you're sending the wrong resource identifier to the *server* as a means of addressing *client* side routing.

I guess, you don't like hashes, and I don't like the idea of hiding state in the browser history - but I can't think of any alternative, so I guess it comes down to a difference in terms of which trade-offs we're willing to accept. 🙂

So this isn't me saying "you're wrong", just that I wish there was a way of satisfying these requirements without having to "pick a poison".

I guess we've hit a wall in terms of what the web platform can do right now. 😉
